# Generated by savvy: do not edit by hand
#
# Note:
#   This wrapper file is named as `000-wrappers.R` so that this file is loaded
#   first, which allows users to override the functions defined here (e.g., a
#   print() method for an enum).

#' @useDynLib ggplot2qgis, .registration = TRUE
#' @keywords internal
NULL

# Check class and extract the external pointer embedded in the environment
.savvy_extract_ptr <- function(e, class) {
  if(is.null(e)) {
    return(NULL)
  }

  if(inherits(e, class)) {
    e$.ptr
  } else {
    msg <- paste0("Expected ", class, ", got ", class(e)[1])
    stop(msg, call. = FALSE)
  }
}

# Prohibit modifying environments

#' @export
`$<-.savvy_ggplot2qgis__sealed` <- function(x, name, value) {
  class <- gsub("__bundle$", "", class(x)[1])
  stop(class, " cannot be modified", call. = FALSE)
}

#' @export
`[[<-.savvy_ggplot2qgis__sealed` <- function(x, i, value) {
  class <- gsub("__bundle$", "", class(x)[1])
  stop(class, " cannot be modified", call. = FALSE)
}


### wrapper functions for GeometryType


`.savvy_wrap_GeometryType` <- function(ptr) {
  e <- new.env(parent = emptyenv())
  e$.ptr <- ptr


  class(e) <- c("ggplot2qgis::GeometryType", "GeometryType", "savvy_ggplot2qgis__sealed")
  e
}


#' Geometry kind of a vector layer: `GeometryType$Point`,
#' `GeometryType$LineString`, or `GeometryType$Polygon`.
#'
#' @export
`GeometryType` <- new.env(parent = emptyenv())
`GeometryType`$`Point` <- .savvy_wrap_GeometryType(0L)
`GeometryType`$`LineString` <- .savvy_wrap_GeometryType(1L)
`GeometryType`$`Polygon` <- .savvy_wrap_GeometryType(2L)

#' @export
`$.ggplot2qgis::GeometryType__bundle` <- function(x, name) {
  if (!name %in% c("Point", "LineString", "Polygon")) {
    stop(paste0("Unknown variant: ", name), call. = FALSE)
  }

  NextMethod()
}

#' @export
`[[.ggplot2qgis::GeometryType__bundle` <- function(x, i) {
  if (is.numeric(i)) {
    stop("GeometryType cannot be subset by index", call. = FALSE)
  }

  if (!i %in% c("Point", "LineString", "Polygon")) {
    stop(paste0("Unknown variant: ", i), call. = FALSE)
  }

  NextMethod()
}

#' @export
`print.ggplot2qgis::GeometryType` <- function(x, ...) {
  idx <- x$.ptr + 1L
  label <- c("Point", "LineString", "Polygon")[idx]
  if (is.na(label)) {
    stop("Unexpected value for GeometryType", call. = TRUE)
  }
  cat("GeometryType::", label, "\n", sep = "")
}


### associated functions for GeometryType



class(`GeometryType`) <- c("ggplot2qgis::GeometryType__bundle", "savvy_ggplot2qgis__sealed")

#' @export
`print.ggplot2qgis::GeometryType__bundle` <- function(x, ...) {
  cat('ggplot2qgis::GeometryType\n')
}

### wrapper functions for QgsBuilder

`QgsBuilder_add_raster_layer` <- function(self) {
  function(`path`, `layer_name`, `srs`, `style`) {
    `style` <- .savvy_extract_ptr(`style`, "ggplot2qgis::RasterStyle")
    invisible(.Call(savvy_QgsBuilder_add_raster_layer__impl, `self`, `path`, `layer_name`, `srs`, `style`))
  }
}

`QgsBuilder_add_vector_layer` <- function(self) {
  function(`path`, `layer_name`, `srs`, `geometry`, `style`) {
    `geometry` <- .savvy_extract_ptr(`geometry`, "ggplot2qgis::GeometryType")
    `style` <- .savvy_extract_ptr(`style`, "ggplot2qgis::VectorStyle")
    invisible(.Call(savvy_QgsBuilder_add_vector_layer__impl, `self`, `path`, `layer_name`, `srs`, `geometry`, `style`))
  }
}

`QgsBuilder_add_xyz_tile_layer` <- function(self) {
  function(`name`, `url`, `zmin`, `zmax`) {
    invisible(.Call(savvy_QgsBuilder_add_xyz_tile_layer__impl, `self`, `name`, `url`, `zmin`, `zmax`))
  }
}

`QgsBuilder_build` <- function(self) {
  function() {
    .Call(savvy_QgsBuilder_build__impl, `self`)
  }
}

`QgsBuilder_set_project_crs` <- function(self) {
  function(`srs`) {
    invisible(.Call(savvy_QgsBuilder_set_project_crs__impl, `self`, `srs`))
  }
}

`QgsBuilder_write_to` <- function(self) {
  function(`path`) {
    invisible(.Call(savvy_QgsBuilder_write_to__impl, `self`, `path`))
  }
}

`.savvy_wrap_QgsBuilder` <- function(ptr) {
  e <- new.env(parent = emptyenv())
  e$.ptr <- ptr
  e$`add_raster_layer` <- `QgsBuilder_add_raster_layer`(ptr)
  e$`add_vector_layer` <- `QgsBuilder_add_vector_layer`(ptr)
  e$`add_xyz_tile_layer` <- `QgsBuilder_add_xyz_tile_layer`(ptr)
  e$`build` <- `QgsBuilder_build`(ptr)
  e$`set_project_crs` <- `QgsBuilder_set_project_crs`(ptr)
  e$`write_to` <- `QgsBuilder_write_to`(ptr)

  class(e) <- c("ggplot2qgis::QgsBuilder", "QgsBuilder", "savvy_ggplot2qgis__sealed")
  e
}


#' Builds a `.qgs` project file.
#'
#' Layers are added bottom-most first: typically a base XYZ tile layer,
#' then vector layers on top of it. Finally, call `$build()` to get the
#' project content as a string, or `$write_to(path)` to write it to a file.
#'
#' @export
`QgsBuilder` <- new.env(parent = emptyenv())

### associated functions for QgsBuilder

`QgsBuilder`$`new` <- function() {
  .savvy_wrap_QgsBuilder(.Call(savvy_QgsBuilder_new__impl))
}


class(`QgsBuilder`) <- c("ggplot2qgis::QgsBuilder__bundle", "savvy_ggplot2qgis__sealed")

#' @export
`print.ggplot2qgis::QgsBuilder__bundle` <- function(x, ...) {
  cat('ggplot2qgis::QgsBuilder\n')
}

### wrapper functions for RasterStyle


`.savvy_wrap_RasterStyle` <- function(ptr) {
  e <- new.env(parent = emptyenv())
  e$.ptr <- ptr


  class(e) <- c("ggplot2qgis::RasterStyle", "RasterStyle", "savvy_ggplot2qgis__sealed")
  e
}


#' How a raster layer is rendered.
#'
#' Create an instance with one of the associated functions:
#'
#' - `RasterStyle$pseudocolor(classes, min, max, stop_offsets, stop_r,
#'   stop_g, stop_b)`: one band colored through a continuous color ramp.
#' - `RasterStyle$pseudocolor_discrete(...)`: the same, but with one flat
#'   color per equal-interval class.
#' - `RasterStyle$multiband(red_band, red_min, red_max, green_band,
#'   green_min, green_max, blue_band, blue_min, blue_max)`: three bands
#'   mapped to the RGB channels. Bands are 1-based; the min/max are the
#'   band statistics QGIS caches as the contrast stretch limits.
#'
#' @export
`RasterStyle` <- new.env(parent = emptyenv())

### associated functions for RasterStyle

`RasterStyle`$`multiband` <- function(`red_band`, `red_min`, `red_max`, `green_band`, `green_min`, `green_max`, `blue_band`, `blue_min`, `blue_max`) {
  .savvy_wrap_RasterStyle(.Call(savvy_RasterStyle_multiband__impl, `red_band`, `red_min`, `red_max`, `green_band`, `green_min`, `green_max`, `blue_band`, `blue_min`, `blue_max`))
}

`RasterStyle`$`pseudocolor` <- function(`classes`, `min`, `max`, `stop_offsets`, `stop_r`, `stop_g`, `stop_b`) {
  .savvy_wrap_RasterStyle(.Call(savvy_RasterStyle_pseudocolor__impl, `classes`, `min`, `max`, `stop_offsets`, `stop_r`, `stop_g`, `stop_b`))
}

`RasterStyle`$`pseudocolor_discrete` <- function(`classes`, `min`, `max`, `stop_offsets`, `stop_r`, `stop_g`, `stop_b`) {
  .savvy_wrap_RasterStyle(.Call(savvy_RasterStyle_pseudocolor_discrete__impl, `classes`, `min`, `max`, `stop_offsets`, `stop_r`, `stop_g`, `stop_b`))
}


class(`RasterStyle`) <- c("ggplot2qgis::RasterStyle__bundle", "savvy_ggplot2qgis__sealed")

#' @export
`print.ggplot2qgis::RasterStyle__bundle` <- function(x, ...) {
  cat('ggplot2qgis::RasterStyle\n')
}

### wrapper functions for Rgb


`.savvy_wrap_Rgb` <- function(ptr) {
  e <- new.env(parent = emptyenv())
  e$.ptr <- ptr


  class(e) <- c("ggplot2qgis::Rgb", "Rgb", "savvy_ggplot2qgis__sealed")
  e
}


#' An opaque RGB color.
#'
#' Create an instance with `Rgb$new(r, g, b)`, where each channel is an
#' integer between 0 and 255.
#'
#' @export
`Rgb` <- new.env(parent = emptyenv())

### associated functions for Rgb

`Rgb`$`new` <- function(`r`, `g`, `b`) {
  .savvy_wrap_Rgb(.Call(savvy_Rgb_new__impl, `r`, `g`, `b`))
}


class(`Rgb`) <- c("ggplot2qgis::Rgb__bundle", "savvy_ggplot2qgis__sealed")

#' @export
`print.ggplot2qgis::Rgb__bundle` <- function(x, ...) {
  cat('ggplot2qgis::Rgb\n')
}

### wrapper functions for VectorStyle


`.savvy_wrap_VectorStyle` <- function(ptr) {
  e <- new.env(parent = emptyenv())
  e$.ptr <- ptr


  class(e) <- c("ggplot2qgis::VectorStyle", "VectorStyle", "savvy_ggplot2qgis__sealed")
  e
}


#' How a vector layer is rendered.
#'
#' Create an instance with one of the associated functions:
#'
#' - `VectorStyle$single(color)`: all features share one symbol.
#' - `VectorStyle$graduated(attribute, classes, min, max, stop_offsets,
#'   stop_r, stop_g, stop_b)`: features are colored by an attribute value
#'   along a color gradient. The gradient is described by control points:
#'   `stop_offsets` are offsets in `0..=1` (the first must be `0` and the
#'   last `1`), and `stop_r`/`stop_g`/`stop_b` are the corresponding color
#'   channels.
#' - `VectorStyle$categorized(attribute, values, colors_r, colors_g,
#'   colors_b, catch_all)`: each discrete attribute value gets its own
#'   color. `catch_all` is an optional `Rgb` for all other values.
#'
#' @export
`VectorStyle` <- new.env(parent = emptyenv())

### associated functions for VectorStyle

`VectorStyle`$`categorized` <- function(`attribute`, `values`, `colors_r`, `colors_g`, `colors_b`, `catch_all` = NULL) {
  `catch_all` <- .savvy_extract_ptr(`catch_all`, "ggplot2qgis::Rgb")
  .savvy_wrap_VectorStyle(.Call(savvy_VectorStyle_categorized__impl, `attribute`, `values`, `colors_r`, `colors_g`, `colors_b`, `catch_all`))
}

`VectorStyle`$`graduated` <- function(`attribute`, `classes`, `min`, `max`, `stop_offsets`, `stop_r`, `stop_g`, `stop_b`) {
  .savvy_wrap_VectorStyle(.Call(savvy_VectorStyle_graduated__impl, `attribute`, `classes`, `min`, `max`, `stop_offsets`, `stop_r`, `stop_g`, `stop_b`))
}

`VectorStyle`$`single` <- function(`color`) {
  `color` <- .savvy_extract_ptr(`color`, "ggplot2qgis::Rgb")
  .savvy_wrap_VectorStyle(.Call(savvy_VectorStyle_single__impl, `color`))
}


class(`VectorStyle`) <- c("ggplot2qgis::VectorStyle__bundle", "savvy_ggplot2qgis__sealed")

#' @export
`print.ggplot2qgis::VectorStyle__bundle` <- function(x, ...) {
  cat('ggplot2qgis::VectorStyle\n')
}

